# Generated by Django 5.2.11 on 2026-02-28 15:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=500)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField()),
                ('door_open_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_type', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('virtual', 'Virtual'), ('hybrid', 'Hybrid')], default='indoor', max_length=20)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('virtual_meeting_url', models.URLField(blank=True, max_length=500)),
                ('virtual_meeting_password', models.CharField(blank=True, max_length=100)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('sold_out', 'Sold Out')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_private', models.BooleanField(default=False, help_text='Private events require invitation code')),
                ('invitation_code', models.CharField(blank=True, max_length=50)),
                ('max_capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_age_requirement', models.PositiveIntegerField(default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('refund_policy', models.TextField(blank=True)),
                ('co_organizers', models.ManyToManyField(blank=True, related_name='co_organized_events', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organized_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'status'], name='events_even_start_d_9e40f1_idx'), models.Index(fields=['city', 'start_date'], name='events_even_city_662f49_idx'), models.Index(fields=['organizer', '-created_at'], name='events_even_organiz_b0e8a9_idx')],
            },
        ),
    ]
