# Generated by Django 5.2.11 on 2026-02-28 15:13

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('ticket_class', models.CharField(choices=[('vip', 'VIP'), ('early_bird', 'Early Bird'), ('general', 'General Admission'), ('student', 'Student'), ('senior', 'Senior'), ('group', 'Group'), ('complimentary', 'Complimentary')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_end_date', models.DateTimeField(blank=True, null=True)),
                ('quantity_available', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('max_per_order', models.PositiveIntegerField(default=10)),
                ('min_per_order', models.PositiveIntegerField(default=1)),
                ('sales_start_date', models.DateTimeField(db_index=True)),
                ('sales_end_date', models.DateTimeField(db_index=True)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('service_fee_fixed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='events.event')),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('ticket_number', models.CharField(db_index=True, default='8261BD2479C9461A878956115E896EB1', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('used', 'Used'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='valid', max_length=20)),
                ('attendee_name', models.CharField(blank=True, max_length=255)),
                ('attendee_email', models.EmailField(blank=True, max_length=254)),
                ('attendee_phone', models.CharField(blank=True, max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='tickets/qrcodes/')),
                ('qr_secret', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('check_in_code', models.CharField(blank=True, max_length=10)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='events.event')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='orders.orderitem')),
                ('ticket_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.tickettype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'ticket_class'], name='tickets_tic_event_i_1edc61_idx'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['event', 'sales_start_date', 'sales_end_date'], name='tickets_tic_event_i_d4e52b_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='tickets_tic_ticket__bf3905_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_secret'], name='tickets_tic_qr_secr_9edc66_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='tickets_tic_event_i_d07e31_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['order', 'status'], name='tickets_tic_order_i_ccd08a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['attendee_email'], name='tickets_tic_attende_c0ecae_idx'),
        ),
    ]
