# Generated by Django 5.2.11 on 2026-03-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(db_index=True, default='EEED34AF02064CF1BCB40C5FFD7BC8A3', max_length=100, unique=True),
        ),
    ]
