# Generated by Django 5.2.11 on 2026-02-28 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='tickets.tickettype'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-order_date'], name='orders_orde_user_id_304132_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['email', '-order_date'], name='orders_orde_email_6d880e_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'expiry_date'], name='orders_orde_status_015404_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'ticket_type'], name='orders_orde_order_i_0603fc_idx'),
        ),
    ]
